permalink: /:categories/:title.html
url: "http://mqvlm.github.io/"
full_name: ""
first_name: ""
last_name: ""
blog_title: "experimentos en processing y otras cosas."
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "mqvlm"
copyright_year: ""
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "mqvlm"
github: "mqvlm"
facebook: "facebook"
linkined_url: ""
